export const LOGIN_ENDPOINT = '/api/auth/login'
export const REGISTER_ENDPOINT = '/api/auth/register'

export const DASHBOARD_USER = '/dashboard/user'
export const DASHBOARD_ROOM = '/dashboard/room'
export const DASHBOARD_BILL = '/dashboard/bill'
export const DASHBOARD_REVENUE = '/dashboard/revenue'

export const LIST_USER = '/user'
export const LIST_TENANT_BY_HOUSE = '/user?houseId=id'
export const LIST_TENANT_BY_ROOM = '/user?roomId=id'
export const DETAIL_USER = '/user/:id'
export const CREATE_MANAGER = '/user/create/manager'
export const CREATE_TENANT = '/user/create/member'
export const EDIT_PASSWORD = '/user/edit/password'
export const EDIT_PROFILE = '/user/edit/profile'

export const LIST_ROOM = '/room'
export const LIST_ROOM_BY_HOUSE = '/room?houseId=id'
export const DETAIL_ROOM = '/room/:id'
export const CREATE_ROOM = '/room/create'
export const DROPDOWN_ROOM_BY_HOUSE = 'room/dropdown?houseId=id'
export const DROPDOWN_ROOM = '/room/dropdown'
export const DROPDOWN_ROOM_FOR_BILL = '/room/dropdown/bill'

export const LIST_HOUSE = '/house'
export const DETAIL_HOUSE = '/house/:id'
export const CREATE_HOUSE = '/house/create'
export const DROPDOWN_HOUSE = '/house/dropdown'

export const LIST_BILL = '/bill'
export const LIST_BILL_BY_ROOM = '/bill?roomId=id'
export const LIST_BILL_BY_HOUSE = '/bill?houseId=id'
export const LIST_BILL_FOR_MEMBER = '/bill?houseId=idHouse&roomId=idRoom'
export const DETAIL_BILL = '/bill/:id'
export const CREATE_BILL = '/bill/create'
